name: Trigger Test Workflow B
on:
  workflow_run:
    workflows: ["POC PR Workflow A (Creates Artifact)"] # Это имя должно ТОЧНО совпадать с name: в Workflow A
    types: [completed]

jobs:
  test_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Workflow B Triggered
        run: echo "Workflow B (Trigger Test) was successfully triggered and executed!"
